# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x07kvstore\"A\n\x10ReplicateRequest\x12\n\n\x02op\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\t\x12\t\n\x01v\x18\x03 \x01(\t\x12\x0b\n\x03ver\x18\x04 \x01(\x03\"0\n\x11ReplicateResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32Q\n\x0bReplication\x12\x42\n\tReplicate\x12\x19.kvstore.ReplicateRequest\x1a\x1a.kvstore.ReplicateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLICATEREQUEST']._serialized_start=30
  _globals['_REPLICATEREQUEST']._serialized_end=95
  _globals['_REPLICATERESPONSE']._serialized_start=97
  _globals['_REPLICATERESPONSE']._serialized_end=145
  _globals['_REPLICATION']._serialized_start=147
  _globals['_REPLICATION']._serialized_end=228
# @@protoc_insertion_point(module_scope)
